<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Barakah.ClothingService</RootNamespace>
    <UserSecretsId>barakah-clothing-service</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Barakah.SharedKernel\Barakah.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Shared\Barakah.Persistence\Barakah.Persistence.csproj" />
    <ProjectReference Include="..\..\Shared\Barakah.TenantContext\Barakah.TenantContext.csproj" />
  </ItemGroup>

</Project>
